apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-affinity-required
spec:
  containers:
    - name: container
      image: nginx:latest
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In # In / NotIn | Exists / DoesNotExist (Delete the values)
                values:
                  - hdd
